### ISSUE TITLE
Discussion about DEBUG_JS_MODULES and DEBUG

### ISSUE THREAD

**Issue by julienw** [devtools-html/rfcs#36] opened 2018-01-31 13:58 UTC
DEBUG_JS_MODULES is enabled by a line in mozconfig:
```
ac_add_options --enable-debug-symbols
```

while DEBUG is enabled by a similar line:
```
ac_add_options --enable-debug
```

DEBUG_JS_MODULES was intended to run some of our code in a "debug" mode but still using a Firefox production build, so much faster. Most of our code that uses DEBUG_JS_MODULES also checks for DEBUG. The direct result is that gecko developers running a DEBUG build without DEBUG_JS_MODULES also gets the same performance penalty.

One direct effect of DEBUG_JS_MODULES is that we load the dev versions of react and other libraries, which are also a lot slower. As said previously, this happens also for simple DEBUG builds.

So there are a few questions to answer about it:

1. Does running the dev version of react help anybody in the team?
2. If yes, should we uncouple DEBUG and DEBUG_JS_MODULES? That would mean that DEBUG wouldn't trigger the dev versions of 3rd-party libraries anymore, we'd have to specify DEBUG_JS_MODULES explicitely. I think this would be a good thing.
3. If no, should we remove the full support for DEBUG_JS_MODULES? This is the good approach if nobody uses it.

**Comment by jasonLaster** [comment] 2018-01-31 14:00
dev version of react has a lot more timing information which is really helpful

**Comment by MikeRatcliffe** [comment] 2018-01-31 14:02
I use it to enable the dev versions of React all the time... couldn't optimize anything properly without it.

**Comment by jryans** [comment] 2018-01-31 14:14
> Does running the dev version of react help anybody in the team?

The warnings from the development build of React are very helpful. Please keep it available as an option somehow.

> If yes, should we uncouple DEBUG and DEBUG_JS_MODULES? That would mean that DEBUG wouldn't trigger the dev versions of 3rd-party libraries anymore, we'd have to specify DEBUG_JS_MODULES explicitely. I think this would be a good thing.

Maybe so, that sounds fine to me. There is already a separate control for debug JS modules:

```
ac_add_options --enable-debug-js-modules
```

Personally, I use this in all my mozconfigs when working on DevTools so that I get React warnings and other things no matter what type of Firefox build I have.

The `DEBUG` mode is aimed at quite a different audience (typically platform engineers working on C++ code) from those who want `DEBUG_JS_MODULES` (typically DevTools engineers working on JS code). While the same person might work in both areas at different times, it is less likely that they are in both areas at once, so we likely don't need them tied together.

> If no, should we remove the full support for DEBUG_JS_MODULES? This is the good approach if nobody uses it.

I think we should keep `DEBUG_JS_MODULES`.

**Comment by julienw** [comment] 2018-01-31 14:21
Thanks, it's pretty clear that the option is used by the team. Then let's focus on question 2:

Should we uncouple DEBUG and DEBUG_JS_MODULES?

That would mean that DEBUG wouldn't trigger the dev versions of 3rd-party libraries anymore, we'd have to specify DEBUG_JS_MODULES explicitely. This is done with a local build through `mozconfig`. I think artifact builds work too.

This is different from what we have now: one could download an available DEBUG build, using mozregression or from a taskcluster run, and run the 3rd-party dev libraries.

**Comment by ochameau** [comment] 2018-01-31 14:32
> Should we uncouple DEBUG and DEBUG_JS_MODULES?

Yes! This is going to speedup devtools a lot on debug builds, which platform developers are using to debug webpages with the devtools and they don't care about debugging react.

I imagine only a couple of DevTools engineers really need this flag and I also imagine them using it only in optimized (i.e. non debug) builds. So I imagine you all pass `--enable-debug-js-modules` in your mozconfig? It would still work as today, but we won't automatically use react-dev on debug builds. If you want to do that, you will have to explicitly pass `--enable-debug-js-modules` in your mozconfig.

**Comment by juliandescottes** [comment] 2018-02-01 17:32
Looks like we are keeping DEBUG_JS_MODULES. 

Let's wait for a few more days to see if anybody objects to decoupling DEBUG_JS_MODULES and DEBUG. If there's no objection before next week, feel free to start logging bugs without waiting for the next RFC review. (cc @julienw)

**Comment by MikeRatcliffe** [comment] 2018-02-06 09:56
At the moment testing in debug mode causes extra logging due to it using the dev version of react and this logging can be very useful. Maybe both DEBUG mode and DEBUG_JS_MODULES could be activated for DEBUG mode tests?

**Comment by juliandescottes** [comment] 2018-02-08 09:30
@MikeRatcliffe you could still use DEBUG_JS_MODULES and get react dev files when running tests locally right? 

I see 3 options:
1. Decouple and don't do anything for tests. React dev files are no longer run in CI. Might get regressions from mass refactors? Logs from try will miss react-dev info.
2. Decouple and force DEBUG_JS_MODULES on CI. Prevents regressions with react-dev files but might introduce different behaviors between local testing and CI.
3. Decouple and force the load of react-dev files in devtools' shared head if running in DEBUG mode. Means we have to ship react+react-dev in DEBUG mode. 

Don't like option 2, because discrepancies between local setup and CI are very frustrating to investigate. I would tend to go for the first approach but I'm doing a lot of react dev debugging.

@julienw  @ochameau @MikeRatcliffe thoughts?

**Comment by julienw** [comment] 2018-02-08 13:29
>  but I'm doing a lot of react dev debugging.

I think you meant "I'm not doing ..." ? :)

From Alexandre:
> I imagine only a couple of DevTools engineers really need this flag and I also imagine them using it only in optimized (i.e. non debug) builds. So I imagine you all pass --enable-debug-js-modules in your mozconfig?

I'd like more answers to this question.

Otherwise I'm in favor of the 1st solution too, but there are some drawbacks that haven't been said yet:

* I noted yesterday that I couldn't specify DEBUG_JS_MODULES in "artifacts" mode, I get an error at `configure` time that it's not compatible with artifacts, is it something known? I think this is a big drawback and we'll need to look at this before decoupling, because I think most if not all of our developers are building in artifacts mode.
* it's not possible to get builds in "debug_js_modules" mode, and especially with mozregression. So I wonder if it's possible (and advisable) to convert this flag into a pref? This would make it easier to trigger from existing builds.

**Comment by jryans** [comment] 2018-02-08 16:15
> So I wonder if it's possible (and advisable) to convert this flag into a pref? This would make it easier to trigger from existing builds.

Converting it to a pref available in all builds would mean shipping both versions of React to users, which I don't think we want to do from a download size perspective.

**Comment by jryans** [comment] 2018-02-08 16:16
I think option 1 sounds fine to me. I only look at the warnings from React Dev during local development. So far, I haven't found them useful (or even noticed them at all...) on CI.

**Comment by MikeRatcliffe** [comment] 2018-02-12 13:19
I agree with @jryans... if a test is failing we can hopefully reproduce it locally so it is not such a big deal for the debug info to be available on try..

**Comment by juliandescottes** [comment] 2018-02-12 14:57
So far looks like option 1 gets the most traction. As @julienw noted, this means we wouldn't be able to get pre-made builds (eg. for mozregression) with debug react files. So this really just makes React dev files usable for local development and investigation only.

This sounds fine to me.

**Comment by juliandescottes** [comment] 2018-02-16 22:03
This RFC has been accepted based on solution 1 proposed above:

> Decouple DEBUG_JS_MODULES and DEBUG and don't do anything specific for tests.

@julienw do you want to create a follow up bug to track the work that needs to be done here?

**Comment by julienw** [comment] 2018-02-23 10:34
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1440609, should we close this bug now ?

**Comment by juliandescottes** [comment] 2018-02-26 10:28
Yes, thanks for creating the follow up! Closing.

**Closed by juliandescottes** 2018-02-26 10:28 UTC
Labels: accepted, proposal

**Comment by juliandescottes** [comment] 2018-04-03 18:57
Bug fixed, closing.
