### ISSUE TITLE
Create a devtools CSS framework

### ISSUE THREAD

**Issue by nt1m** [devtools-html/rfcs#54] opened 2018-11-07 16:54 UTC
One thing I've noticed frequently is that some components are styled in multiple places with different CSS, which leads to design inconsistency, code duplication and eventually regressions.

One example are plain text inputs (that doesn't include search boxes):

- There's the [common.css class `.devtools-textinput`](https://searchfox.org/mozilla-central/rev/6e0e603f4852b8e571e5b8ae133e772b18b6016e/devtools/client/themes/common.css#442) which is used in the old connect page, the filter editor tooltip and the class list panel in the rules view.

- There's the font editor input styling: https://searchfox.org/mozilla-central/rev/6e0e603f4852b8e571e5b8ae133e772b18b6016e/devtools/client/themes/fonts.css#243-284

- There's the edit and resend input styling (which aims to imitate the font editor styling): https://searchfox.org/mozilla-central/rev/6e0e603f4852b8e571e5b8ae133e772b18b6016e/devtools/client/netmonitor/src/assets/styles/CustomRequestPanel.css

- And the new debugger which has its own CSS

Another example are twisties:

- There's the theme-twisty class, used in most places. 

- There's the .arrow class used in the console output when expanding objects (which is broken at the moment): 
<img width="330" alt="screen shot 2018-11-07 at 5 32 48 pm" src="https://user-images.githubusercontent.com/1795135/48145453-2e620800-e2b3-11e8-8c7b-b58db2f42e8a.png">

- The storage inspector tree styles the twisty on the ::before pseudo-element

- The new changes panel uses unicode characters

- The debugger uses its own inline SVG

I could give more examples, but my point is that there is clearly a problem in the way CSS organized.

Using the common classes in common.css more often and maybe documenting those classes so more people know about them would be a good start

Otherwise, creating a new framework from scratch can be a good idea too.
I had an attempt on this a year ago: https://nt1m.github.io/devtools-framework/demo/
I'm sharing it again today, because I see the problems cited above popping up more often.

This framework would solve the following problems:

- Ability to create a new tool layout quickly without having to write any tool-specific CSS regardless of whether you use React, vanilla JS or simply HTML

- Prevent frequent bugs like "XXX does not look right on the dark theme"

- Reduce code duplication

- More design consistency

**Comment by MikeRatcliffe** [comment] 2018-11-07 18:11
Great idea!

We have had a few runs at this in the past (at least on the CSS side) so we are probably due one again.

The problem has always been that if somebody is not sure how to do something they often turn out implementing it themselves.

Having some kind of library that we use to create these things would make a heckovalotta sense in my opinion.

**Comment by belen-albeza** [comment] 2018-11-08 11:20
Hi,

+1 to having a common framework to use across DevTools. I have some comments, though:

- I'm not sure if all [Photon custom components for DevTools](https://firefox-dev.tools/photon/) following that have been spec'd are implemented in `common.css`. Also, there's a bunch which are still marked as "Draft" and I don't know if more components are planned to be added there. It would be nice to make sure all the components that have been spec'd are in this framework, and to finish any remaining UX definition that needs a wrap up.
- The CSS selectors used in `common.css` are not ideal. We have selectors such as:
  ```
  .theme-dark .devtools-searchinput > .textbox-input-box > .textbox-search-icons > .textbox-search-clear
  ```
  This selector is so specific that, if some customization needs to be done to the element with `.textbox-search-clear`, it would be almost impossible to override that rule without using `!important` –which brings its own problems.
- **I'd opt for writing a new framework** –instead of using what's already in `common.css`– with CSS rules that are easy to override if needed. The [approach we began to adopt in the Application panel](https://gist.github.com/belen-albeza/86a8df1ae2a6f7e21a65e17e0131dc3a), and now are using in `about:debugging` is using [BEM](http://getbem.com/introduction/)-like selectors to achieve this. There's also a [project in Mozilla to create Photon components](https://github.com/FirefoxUX/photon-components-web) which is using BEM as well.
- This new framework should be properly documented so people know: 1) which components are available; 2) what is the markup they have to use; 3) which CSS rules implement that styling.

**Comment by captainbrosset** [comment] 2018-11-09 10:33
I'm a bit hesitant with using the work framework here. It scares me a little bit, and here's why:

Fixing the existing issues that @nt1m listed (input fields, toggle buttons, twisties) has immediate benefits to everybody (more consistency, less code to maintain, better quality), and can be done in a framework-like way (e.g. by moving the code to a central place, documenting it, removing other copies, maybe adding tests or tools that prevent people from creating their own versions of it again).

This way, from the inside-out, we can fix the things that need it the most, and end up with a (maybe tiny at first but) very useful library of classes/components that people can just use off the shelf when creating new UI.

Creating a new framework from scratch always sounds scary and costly to me.

**Comment by sole** [comment] 2018-11-09 13:39
Sharing the concerns from Patrick. Also, for a new framework to be considered successful, all the code in DevTools should be using it, which would involve lots of time spent updating every single panel. We already underwent a very significant refactoring during the XUL → HTML conversion, and one of the things we learnt when we did the retrospective was that it worked better when we refactored things from the inside out, and  ensured the functionality was never broken. One thing at a time, rather than a framework upfront.

I see this as a long time effort, rather than a one-off task. And I certainly don't see this as something that you tackle by writing code upfront; you would need to start by doing an inventory of what's already there, finding patterns and similar but not quite the same elements, etc. So a design system.

Fortunately, @violasong  & @mcroud  are already on this: https://firefox-dev.tools/photon/

I do not intend to discount the frustration that engineers feel when working on each panel or the frustration users might be feeling when things are not quite consistent. It would actually be useful to reframe this discussion to hear the kind of problems engineers most often face when writing CSS for DevTools. Perhaps that'll help us establish a direction for this "better CSS" initiative.

For example:

* the fact that we have two themes and lots of duplication and overriding can make updating global look & feel really painful
* also some users have very specific theme preferences, and we have no way of letting them customise the colours we use. If we used variables in a "sensible" way perhaps we would open the door to this kind of customisations. Perhaps that might even make it easier for us in general.

**Comment by gregtatum** [comment] 2018-11-09 15:13
Another risk, is for tools that aren't being actively worked on. Most of the regressions around the memory and performance panel have been around CSS changes from shared files. It's difficult to check every single panel, in every single configuration, to make sure that a small CSS change doesn't affect everything. This is also something that can't really be covered by tests. More isolated styles help protect in this, and require an explicit update process. Of course that comes at the cost of some consistency.

In addition, the more that styles are shared, the more that they are re-used and extended with additional rules. This can be brittle across many tools, with various authors, and various usage levels for the tools. It's more difficult to figure out the styling of a component when two or more classes are being applied to it.

Generally I've been scared of shared CSS systems. My preference is typically to have documented style guides like the [Photon guide](https://design.firefox.com/photon/welcome.html) that can be applied freely to individual tools.

**Comment by nt1m** [comment] 2018-11-11 20:00
> Many of the regressions around the memory and performance panel have been around CSS changes from shared files. 

I haven't noticed any regressions in the memory panel in the last few months, but I've definitively noticed some in the performance panel. Correct me if I'm wrong though. The reason why the memory panel is not/less affected than the perf panel is because the perf panel uses XUL instead of HTML. The shared CSS changes are usually made with the HTML tools in mind, so that problem should go away when the perf panel gets replaced.

> If we used variables in a "sensible" way perhaps we would open the door to this kind of customisations. Perhaps that might even make it easier for us in general.

+1, I noticed the variable usage in devtools is quite crazy and perhaps documenting when to use variables in some guide would be helpful.

> Fixing the existing issues that @nt1m listed (input fields, toggle buttons, twisties) has immediate benefits to everybody (more consistency, less code to maintain, better quality), and can be done in a framework-like way (e.g. by moving the code to a central place, documenting it, removing other copies, maybe adding tests or tools that prevent people from creating their own versions of it again).

I support @captainbrosset's approach too, since I agree that creating a framework from scratch can be haunting, especially to make it compatible with XUL+HTML. I was thinking of following the same CSS coding style that Firefox in-content pages use: https://searchfox.org/mozilla-central/source/toolkit/themes/shared/in-content/common.inc.css

**Comment by nt1m** [comment] 2018-11-11 20:14
> The CSS selectors used in common.css are not ideal. We have selectors such as: 

Yes, these are for old XUL elements. A lot of this CSS is old and was copied from old toolkit code. I agree the selectors are not great.

> I'd opt for writing a new framework –instead of using what's already in common.css– with CSS rules that are easy to override if needed. The approach we began to adopt in the Application panel, and now are using in about:debugging is using BEM-like selectors to achieve this. There's also a project in Mozilla to create Photon components which is using BEM as well.

I'm personally not a big fan of BEM due to its strange naming conventions `--`, `_`, `-`.  It's not necessarily useful most of the time to have those extra conventions and makes the CSS less "human" to read.

For naming conventions, usages of classes, I like: 
https://github.com/JanitorTechnology/janitor/blob/master/static/css/janitor-new.css

For CSS variable usage, this is pretty good: https://searchfox.org/mozilla-central/source/toolkit/themes/shared/in-content/common.inc.css

**Comment by juliandescottes** [comment] 2018-11-16 09:36
We tried to review this RFC yesterday but it's difficult to accept or reject it because it lacks a concrete proposal. Looking at the conversation, it seems most people agree we have issues with CSS inconsistencies, both between panels and themes. 

We propose to focus this RFC on sharing components or components styles. If someone has a clear proposal (@ntim or anyone else here) and is willing to drive the effort, please share it here so that we can decide if we go for it or not. It can be a set of shared react components, CSS guidelines, a style guide. Ideally with an example of how it would look like for one of our components.

For the other issues raised here, such as reworking our CSS variables, it seems like it can be a separate discussion. So same idea, let's open another RFC if anyone has a detailed proposal on how we should change our CSS variables.

**Comment by fvsch** [comment] 2018-11-22 12:08
I'm all for having more reusable components, ideally with their own CSS file rather than putting 50 of them in a `common.css`.

Despite their verbosity, naming guidelines like BEM also have the advantage of being industry standards and leaving not much to individual taste. I've had good results with [teaching BEM-like guidelines](https://kaliop.github.io/frontend-style-guide/2.0/css/#components) in my current team, though it works best with dedicated CSS devs rather than trying to teach it to "full-stack" devs :P

**Comment by juliandescottes** [comment] 2018-11-28 09:50
There are no clear proposals discussed here at the moment. I will close this for now because it is not actionable. The amount of comments clearly shows we agree there's an issue with CSS in DevTools, so again if anyone feels like proposing something concrete we can do, feel free to either reopen this, or create a new RFC. 

Thanks!

**Closed by juliandescottes** 2018-11-28 09:50 UTC
